@Library("jenlib") _

Map<String, Object> pipelineOptions = [
		projects: ["pynn-brainscales"],
		container: [app: "dls"],
		notificationChannel: "#dls-software"
]

if (!isTriggeredByGerrit()) {
	pipelineOptions << [
			testSlurmResource: [partition: "cube", wafer: 62, "fpga-without-aout": 3],
			preTestHook: { configureHxCubeBitfile() },
			testOptions: "--test-execall -j1"
	]
}

wafDefaultPipeline(pipelineOptions)

runOnSlave(label: "frontend") {
    archiveArtifacts(artifacts: "pynn-brainscales/brainscales2/plot_isi_calib.pdf",
                     allowEmptyArchive: true)
}
